### PR TITLE
Quick Fix: clone via HTTPS

### PR DESCRIPTION
**Pull request by NotAFile**

### CODE REVIEW

**Comment by LeComm** [comment]
Don't want git to mess up my stuff but I applied your suggestion to my code in the latest commit.

**Comment by oldmud0** [comment]
This individual appears to know what he is doing.

**Comment by NotAFile** [comment]
heh somebody doesn't know about `rebase`

**Comment by LeComm** [comment]
heh somebody doesn't know that I don't give a shit

**Pull request closed without merging**
